{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7.jar",
          "url": "spring-boot-buildpack-platform-2.5.7.jar",
          "size": 237696,
          "sha512": "d0d9ec66f18536fc533b4e42099fc32f1f04ecfef760cfec16cbef819cc59518b2154e10ac629af2b37e4a3afe13c16839972471b6efee95d1c0b3bdda75a794",
          "sha256": "9e4382686dc21365d7156b7a3cd45460840009bef2c7e29ccff1fe3570d4da20",
          "sha1": "ee6ac69d5aad0b1c13c138a05f8f33a02384cfbe",
          "md5": "6ba96cc8bffc03782f30ecba9b497d2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7.jar",
          "url": "spring-boot-buildpack-platform-2.5.7.jar",
          "size": 237696,
          "sha512": "d0d9ec66f18536fc533b4e42099fc32f1f04ecfef760cfec16cbef819cc59518b2154e10ac629af2b37e4a3afe13c16839972471b6efee95d1c0b3bdda75a794",
          "sha256": "9e4382686dc21365d7156b7a3cd45460840009bef2c7e29ccff1fe3570d4da20",
          "sha1": "ee6ac69d5aad0b1c13c138a05f8f33a02384cfbe",
          "md5": "6ba96cc8bffc03782f30ecba9b497d2f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7-javadoc.jar",
          "url": "spring-boot-buildpack-platform-2.5.7-javadoc.jar",
          "size": 291365,
          "sha512": "0a2f529d9aa232016d2febd62a425d9462fdae1ee91f3653dc8d094af2b95858780060a1d3ebd55d489d61665ded1baad30f8b6eacdf34ec7cbda1d9ab3277ed",
          "sha256": "f438efcab840003ce9f9316deedcdeb30c9e669de697ff979a521372e18d5865",
          "sha1": "219e4e08a8f535c75877652c234774ff9211b5f9",
          "md5": "837bb869bf584a853b2a725b6a1f2555"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7-sources.jar",
          "url": "spring-boot-buildpack-platform-2.5.7-sources.jar",
          "size": 155442,
          "sha512": "29d309a95fc6385790fb6c38dd36303082ee24e1216db9566da281652728e95903dedab72beb2a8a6cd8b59873a6f09eb59673bdada0f47d41402738f8ce7d78",
          "sha256": "f490e293abd2e5e5fa387a8d6d98a14a255b0a613e526181d8e3a9695a41c1c0",
          "sha1": "cf8d6d40479603158210cabedf59451002db753c",
          "md5": "019473008308bcadc0684c7f28a754eb"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7.jar",
          "url": "spring-boot-buildpack-platform-2.5.7.jar",
          "size": 237696,
          "sha512": "d0d9ec66f18536fc533b4e42099fc32f1f04ecfef760cfec16cbef819cc59518b2154e10ac629af2b37e4a3afe13c16839972471b6efee95d1c0b3bdda75a794",
          "sha256": "9e4382686dc21365d7156b7a3cd45460840009bef2c7e29ccff1fe3570d4da20",
          "sha1": "ee6ac69d5aad0b1c13c138a05f8f33a02384cfbe",
          "md5": "6ba96cc8bffc03782f30ecba9b497d2f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.5.7.jar",
          "url": "spring-boot-buildpack-platform-2.5.7.jar",
          "size": 237696,
          "sha512": "d0d9ec66f18536fc533b4e42099fc32f1f04ecfef760cfec16cbef819cc59518b2154e10ac629af2b37e4a3afe13c16839972471b6efee95d1c0b3bdda75a794",
          "sha256": "9e4382686dc21365d7156b7a3cd45460840009bef2c7e29ccff1fe3570d4da20",
          "sha1": "ee6ac69d5aad0b1c13c138a05f8f33a02384cfbe",
          "md5": "6ba96cc8bffc03782f30ecba9b497d2f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.5.7"
        }
      ]
    }
  ]
}
