{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7.jar",
          "url": "spring-boot-starter-tomcat-2.5.7.jar",
          "size": 4797,
          "sha512": "c8ec7f248b08ec74d05e19773e5d8d2dde432ce8c56948ecf3a579ebaae237c7c56ae7b4d23036c91d38086da1564cbbf78c9a39a011ade62c0fcc3da432e19a",
          "sha256": "f38b01545fd9445788d85592af1d467b33b06d0f4d617d23261087c203b39180",
          "sha1": "87f17e1ffb76bc0143a7e9536f64c0c387f4c962",
          "md5": "7865b0432798717fecff2a1fbec34112"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.55"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7.jar",
          "url": "spring-boot-starter-tomcat-2.5.7.jar",
          "size": 4797,
          "sha512": "c8ec7f248b08ec74d05e19773e5d8d2dde432ce8c56948ecf3a579ebaae237c7c56ae7b4d23036c91d38086da1564cbbf78c9a39a011ade62c0fcc3da432e19a",
          "sha256": "f38b01545fd9445788d85592af1d467b33b06d0f4d617d23261087c203b39180",
          "sha1": "87f17e1ffb76bc0143a7e9536f64c0c387f4c962",
          "md5": "7865b0432798717fecff2a1fbec34112"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7.jar",
          "url": "spring-boot-starter-tomcat-2.5.7.jar",
          "size": 4797,
          "sha512": "c8ec7f248b08ec74d05e19773e5d8d2dde432ce8c56948ecf3a579ebaae237c7c56ae7b4d23036c91d38086da1564cbbf78c9a39a011ade62c0fcc3da432e19a",
          "sha256": "f38b01545fd9445788d85592af1d467b33b06d0f4d617d23261087c203b39180",
          "sha1": "87f17e1ffb76bc0143a7e9536f64c0c387f4c962",
          "md5": "7865b0432798717fecff2a1fbec34112"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7.jar",
          "url": "spring-boot-starter-tomcat-2.5.7.jar",
          "size": 4797,
          "sha512": "c8ec7f248b08ec74d05e19773e5d8d2dde432ce8c56948ecf3a579ebaae237c7c56ae7b4d23036c91d38086da1564cbbf78c9a39a011ade62c0fcc3da432e19a",
          "sha256": "f38b01545fd9445788d85592af1d467b33b06d0f4d617d23261087c203b39180",
          "sha1": "87f17e1ffb76bc0143a7e9536f64c0c387f4c962",
          "md5": "7865b0432798717fecff2a1fbec34112"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.5.7-javadoc.jar",
          "size": 4745,
          "sha512": "acd3d9d6cd3d5ecd26c40b7fbdc6515aae42d3cc3ed936f7d713412305d19064dffb10b154464a53ebd0b0011956f0637f70b33eedc9075cdcb587d6851aa1fc",
          "sha256": "d098788ac9873548dd8f0a886220139a0c5793a39120e14f2a96d88620c3fb4c",
          "sha1": "5c8bcebee56ade83c5bb4c58d43dd0bb878aa15e",
          "md5": "f26fa2c393d4e573798e07bd3c8c0311"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.7-sources.jar",
          "url": "spring-boot-starter-tomcat-2.5.7-sources.jar",
          "size": 4744,
          "sha512": "a84ee296f162d139cfe0c04791048a3d42c970fe04160f8e8fc0f07e7a3b917bee97bc159f9a4b6181d313c330d829c1df7702074df45532fdc0e12973f82561",
          "sha256": "a656df9d1fcdc2b0f9ae94033022b01c031eafe5eca5779a5485003acc43e426",
          "sha1": "8c8c6507883a48f2e376800619e8d43f5eb114d1",
          "md5": "690d22fb1564221174ee29215aef0fe5"
        }
      ]
    }
  ]
}
