{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        },
        {
          "group": "org.springframework",
          "module": "spring-context"
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.3.1.RELEASE.jar",
          "url": "spring-boot-2.3.1.RELEASE.jar",
          "size": 1118833,
          "sha512": "013b9708de532783c83f024d86ef79e9e74b2d2f049bcf372119c441849387801b9cf926f2a8cbe216c28ce4cb528ba5020c4d165f66ee9fb8440e0bf8332f05",
          "sha256": "abed24750af5ac26d2e3e92dc2f715bf418563c697a8f1ae6c9a806b3b4a0901",
          "sha1": "ce8d8b6838ecceb68962b975b18682f4237ccf71",
          "md5": "57c16c5f18a57b4db8874ea8e7ef204b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        },
        {
          "group": "org.springframework",
          "module": "spring-context"
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.3.1.RELEASE.jar",
          "url": "spring-boot-2.3.1.RELEASE.jar",
          "size": 1118833,
          "sha512": "013b9708de532783c83f024d86ef79e9e74b2d2f049bcf372119c441849387801b9cf926f2a8cbe216c28ce4cb528ba5020c4d165f66ee9fb8440e0bf8332f05",
          "sha256": "abed24750af5ac26d2e3e92dc2f715bf418563c697a8f1ae6c9a806b3b4a0901",
          "sha1": "ce8d8b6838ecceb68962b975b18682f4237ccf71",
          "md5": "57c16c5f18a57b4db8874ea8e7ef204b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-2.3.1.RELEASE-javadoc.jar",
          "size": 1715119,
          "sha512": "ac6078f51c3d375a9ddf4aa34c06cb3b819f84e2a3b1cfe56f936b1aac6f7195334dab0b466acc6b23a7f95fd4ecf1ef823a8acc5ad835e6fec918424f36f0b1",
          "sha256": "6f68dab78fbe1cdc0b1598dac004b876390419a02aa575048314ae7ce837e8e2",
          "sha1": "4cf66c03b59894323fd75d752c9de69e287b61fd",
          "md5": "99e90a555ffb764b92c1bd5a91c7cf61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-2.3.1.RELEASE-sources.jar",
          "size": 823520,
          "sha512": "eb6f3ff326e1198cb1342e3a024023db020c86c6585c2f78ec0215d8afe939637ddafeb41621bb49fe2be2763996b9e754794c425fb1516fe776612429dcee3b",
          "sha256": "997bb74ab674217de2bcfcc7df0b47e0f6d069a70fdff239e1bf6eab73b11bce",
          "sha1": "f897e0bd34b2966aa1b8ccb1593dba62470c24fc",
          "md5": "e707981e49fa5315111f3976b4a19d71"
        }
      ]
    }
  ]
}
