{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.0.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7.jar",
          "url": "spring-boot-starter-validation-2.5.7.jar",
          "size": 4769,
          "sha512": "82332ece29e1ffd20a835b5824faef3cb83ba012b203fb7f035c7539047862f48be8073d773f1656833aa45739605c434a3be903020d6a18693e6687aa1e0f1a",
          "sha256": "063c192cc04a8ab1ac9464b4475c0b21b54f588631c10f067ce8d92a28057536",
          "sha1": "6302c6a44c80fe9f004bb92f217f0c596852940b",
          "md5": "a0179adeb1509c7c6272a7ae0ff9cbf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.55"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "6.2.0.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7.jar",
          "url": "spring-boot-starter-validation-2.5.7.jar",
          "size": 4769,
          "sha512": "82332ece29e1ffd20a835b5824faef3cb83ba012b203fb7f035c7539047862f48be8073d773f1656833aa45739605c434a3be903020d6a18693e6687aa1e0f1a",
          "sha256": "063c192cc04a8ab1ac9464b4475c0b21b54f588631c10f067ce8d92a28057536",
          "sha1": "6302c6a44c80fe9f004bb92f217f0c596852940b",
          "md5": "a0179adeb1509c7c6272a7ae0ff9cbf4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7.jar",
          "url": "spring-boot-starter-validation-2.5.7.jar",
          "size": 4769,
          "sha512": "82332ece29e1ffd20a835b5824faef3cb83ba012b203fb7f035c7539047862f48be8073d773f1656833aa45739605c434a3be903020d6a18693e6687aa1e0f1a",
          "sha256": "063c192cc04a8ab1ac9464b4475c0b21b54f588631c10f067ce8d92a28057536",
          "sha1": "6302c6a44c80fe9f004bb92f217f0c596852940b",
          "md5": "a0179adeb1509c7c6272a7ae0ff9cbf4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7.jar",
          "url": "spring-boot-starter-validation-2.5.7.jar",
          "size": 4769,
          "sha512": "82332ece29e1ffd20a835b5824faef3cb83ba012b203fb7f035c7539047862f48be8073d773f1656833aa45739605c434a3be903020d6a18693e6687aa1e0f1a",
          "sha256": "063c192cc04a8ab1ac9464b4475c0b21b54f588631c10f067ce8d92a28057536",
          "sha1": "6302c6a44c80fe9f004bb92f217f0c596852940b",
          "md5": "a0179adeb1509c7c6272a7ae0ff9cbf4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-validation-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-validation-2.5.7-javadoc.jar",
          "size": 4747,
          "sha512": "ad4af868f8264be18f472fd2abf63edeeac4ab9f18b4209c88867f1678e3455dd189d81d85739f005b5341f789d9ce7b53569f69980f6b079ccf82250477d296",
          "sha256": "6bed7aad62ede1c436e07bce9d1ab3e3d36bd0396c16f3d5f7c2856ca0d864f4",
          "sha1": "29e9d980797918d81ff905001084d727b1def072",
          "md5": "e143a06001d9c8fdb2abe18e8bcdddc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.5.7-sources.jar",
          "url": "spring-boot-starter-validation-2.5.7-sources.jar",
          "size": 4746,
          "sha512": "56c24faa064471db8daa499733b2c11d59ed12631ee8092993b2ea06b7567bdf0460c1ca3c727aa9cdf60dd1d78b9b9007747c9ce6340a3c8ddd115727523308",
          "sha256": "967fe05533a697a0a6386ab988eb0720d13d5e8d3e6a1e7e9943232b1d5dec41",
          "sha1": "2566786b3f20db6fe962e036ddd25a9ab8c8f39a",
          "md5": "c48fd653e177c86702f6a77d1994210a"
        }
      ]
    }
  ]
}
