{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-messaging-5.3.13.jar",
          "url": "spring-messaging-5.3.13.jar",
          "size": 567355,
          "sha512": "8d47ed3c30cea8c5c46a88fb4c3e70472ce7423970b27c8c87494f357b7cd421cba455ce564b95b8a3709d253d7db3520b7b6b4bdbab22a9237d4783384e86a5",
          "sha256": "d080d6083aeba901023c60118ad212034c5861e119106438b68ca71ba5cb2123",
          "sha1": "541b3e6462b5cc6e8cb59af25ca1743db2436cab",
          "md5": "f74195e3ce1d4ead8509ef36886af2be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-messaging-5.3.13.jar",
          "url": "spring-messaging-5.3.13.jar",
          "size": 567355,
          "sha512": "8d47ed3c30cea8c5c46a88fb4c3e70472ce7423970b27c8c87494f357b7cd421cba455ce564b95b8a3709d253d7db3520b7b6b4bdbab22a9237d4783384e86a5",
          "sha256": "d080d6083aeba901023c60118ad212034c5861e119106438b68ca71ba5cb2123",
          "sha1": "541b3e6462b5cc6e8cb59af25ca1743db2436cab",
          "md5": "f74195e3ce1d4ead8509ef36886af2be"
        }
      ]
    }
  ]
}
