server:
  port: 8080
logging:
  level:
    root: info
spring:
  application:
    name: config-client
  cloud:
    config:
      import: optional:configserver:http://localhost:8888
      enabled: true
      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"


