{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator-autoconfigure",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "size": 534884,
          "sha512": "4d0e9496d46c47fec39bd5a1085178e71a005035d2a3b959e1ee7b24187d04f192b387809b37b82331deb5a62d5e89cf6b8ec499939b356ba58704ab52f71646",
          "sha256": "786c70818dd67d4a196d94e5373b89afa90077d4120ee6b2bd03d8c1b6af2aef",
          "sha1": "9b206399f53356b50ff0146379702ee37637ef74",
          "md5": "a383a210d4abd53facd98f6ed14cee79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "size": 534884,
          "sha512": "4d0e9496d46c47fec39bd5a1085178e71a005035d2a3b959e1ee7b24187d04f192b387809b37b82331deb5a62d5e89cf6b8ec499939b356ba58704ab52f71646",
          "sha256": "786c70818dd67d4a196d94e5373b89afa90077d4120ee6b2bd03d8c1b6af2aef",
          "sha1": "9b206399f53356b50ff0146379702ee37637ef74",
          "md5": "a383a210d4abd53facd98f6ed14cee79"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "size": 534884,
          "sha512": "4d0e9496d46c47fec39bd5a1085178e71a005035d2a3b959e1ee7b24187d04f192b387809b37b82331deb5a62d5e89cf6b8ec499939b356ba58704ab52f71646",
          "sha256": "786c70818dd67d4a196d94e5373b89afa90077d4120ee6b2bd03d8c1b6af2aef",
          "sha1": "9b206399f53356b50ff0146379702ee37637ef74",
          "md5": "a383a210d4abd53facd98f6ed14cee79"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7.jar",
          "size": 534884,
          "sha512": "4d0e9496d46c47fec39bd5a1085178e71a005035d2a3b959e1ee7b24187d04f192b387809b37b82331deb5a62d5e89cf6b8ec499939b356ba58704ab52f71646",
          "sha256": "786c70818dd67d4a196d94e5373b89afa90077d4120ee6b2bd03d8c1b6af2aef",
          "sha1": "9b206399f53356b50ff0146379702ee37637ef74",
          "md5": "a383a210d4abd53facd98f6ed14cee79"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7-javadoc.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7-javadoc.jar",
          "size": 1065442,
          "sha512": "705c37674430a5ded89e2d2781b9aac42560f9fd07f06a0060d4f7759a43c829c9961bd40f956c1b926fda5edaaf5bee52341fc6e4e7378ac5e5a9e8f27030e1",
          "sha256": "7c9c2bcd5764684c905c4bb95f64c828c61efcf26e6cea8634483bc8fa2cf8ab",
          "sha1": "b3cfd51fa3c04753560adbd65f1e06eb8e5875b2",
          "md5": "dc37259c0880161411e6d14f038c2f29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-2.5.7-sources.jar",
          "url": "spring-boot-actuator-autoconfigure-2.5.7-sources.jar",
          "size": 428837,
          "sha512": "f6b90244b78ed6a0083a4a3a6ad6eda9ef917914e491e250d91259b318bd72d47eb8dbd017e1fd0b6f8b20cbd954d19a71c10b7ae4313e6d98c89bf61d248f4d",
          "sha256": "331f92b50a2eda93d92c6ecef23f48704227860d238cd353ff449e4897853a08",
          "sha1": "64d1ba9590cf167d1f4c26154f46e774723afb29",
          "md5": "5c9392038a24975be1d828821c44d3dc"
        }
      ]
    }
  ]
}
