{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.13.jar",
          "url": "spring-beans-5.3.13.jar",
          "size": 697210,
          "sha512": "28c439c59589d3eea39749dcdf7af0448964cbcbc46bc5a9e82fc6af7355c3526529a890224135172cebbfbf50878d0219c5fab8edd8a2d222b8d2b236f6f00a",
          "sha256": "7d0d4e4da5c9e2168ec21d49a94668a1c8a1d22fdae7ddaffc899f3a2859e306",
          "sha1": "1d90c96b287253ec371260c35fbbea719c24bad6",
          "md5": "b8081de4b093b3af9e1ed3bc827b4ce7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.13.jar",
          "url": "spring-beans-5.3.13.jar",
          "size": 697210,
          "sha512": "28c439c59589d3eea39749dcdf7af0448964cbcbc46bc5a9e82fc6af7355c3526529a890224135172cebbfbf50878d0219c5fab8edd8a2d222b8d2b236f6f00a",
          "sha256": "7d0d4e4da5c9e2168ec21d49a94668a1c8a1d22fdae7ddaffc899f3a2859e306",
          "sha1": "1d90c96b287253ec371260c35fbbea719c24bad6",
          "md5": "b8081de4b093b3af9e1ed3bc827b4ce7"
        }
      ]
    }
  ]
}
