{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7.jar",
          "size": 182322,
          "sha512": "5420e209b11a8092964f3f78960ae551daf115b73fb2352e98cd6a0838befd751409d06c0002ae035985da015cf59da86bbc2fba5d3410e95e759148b417136c",
          "sha256": "fa0bfee94b0404f6d6c50c65c133bf80582b1f68134d33b8a0cdc6b37280ee38",
          "sha1": "bdd85d4b1641ea08c04b568f2a548b85482d14fd",
          "md5": "9e179f1f1bad9c04fecd4dc2fadb5d4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7.jar",
          "size": 182322,
          "sha512": "5420e209b11a8092964f3f78960ae551daf115b73fb2352e98cd6a0838befd751409d06c0002ae035985da015cf59da86bbc2fba5d3410e95e759148b417136c",
          "sha256": "fa0bfee94b0404f6d6c50c65c133bf80582b1f68134d33b8a0cdc6b37280ee38",
          "sha1": "bdd85d4b1641ea08c04b568f2a548b85482d14fd",
          "md5": "9e179f1f1bad9c04fecd4dc2fadb5d4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7-javadoc.jar",
          "size": 355060,
          "sha512": "2d08b17d1a808665c3b5d18e8791e99cc32b7bb1252b8bfe43fe167ebe93cb7a26fac71edf1fc8cbbb8f955888d73530ebd9bebdc838fc9d1af35dee506110c5",
          "sha256": "2c493a40acdbf107f6f11e0752f8cd8334751f0e68cc9b26b4b8b4e64464e4d3",
          "sha1": "4f42247422a4104d592e32873dfbe103e571eaef",
          "md5": "931595b4f06e9c6835c9585f31ad3556"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7-sources.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7-sources.jar",
          "size": 176358,
          "sha512": "3dfaf96690defddf0e4ab8335d7d4b09ce9bfdbe24cf3db881f0e48975921ac07f8c11cbbeed93c24a5aaf244c7c1e25cb690b4d6f365b69f00bc56eb0e547fa",
          "sha256": "63ca18b26c2dee77699b74403f248b326a59e196dd9a2ec2ad5b1596b261b2e0",
          "sha1": "1d6e03073444b95c42f5806fdafec162b6d33da8",
          "md5": "2e47180cb091a3d34c302ae092f851e1"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7.jar",
          "size": 182322,
          "sha512": "5420e209b11a8092964f3f78960ae551daf115b73fb2352e98cd6a0838befd751409d06c0002ae035985da015cf59da86bbc2fba5d3410e95e759148b417136c",
          "sha256": "fa0bfee94b0404f6d6c50c65c133bf80582b1f68134d33b8a0cdc6b37280ee38",
          "sha1": "bdd85d4b1641ea08c04b568f2a548b85482d14fd",
          "md5": "9e179f1f1bad9c04fecd4dc2fadb5d4b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-2.5.7.jar",
          "url": "spring-boot-test-autoconfigure-2.5.7.jar",
          "size": 182322,
          "sha512": "5420e209b11a8092964f3f78960ae551daf115b73fb2352e98cd6a0838befd751409d06c0002ae035985da015cf59da86bbc2fba5d3410e95e759148b417136c",
          "sha256": "fa0bfee94b0404f6d6c50c65c133bf80582b1f68134d33b8a0cdc6b37280ee38",
          "sha1": "bdd85d4b1641ea08c04b568f2a548b85482d14fd",
          "md5": "9e179f1f1bad9c04fecd4dc2fadb5d4b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "2.5.7"
        }
      ]
    }
  ]
}
