{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path"
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api"
        },
        {
          "group": "org.assertj",
          "module": "assertj-core"
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter"
        },
        {
          "group": "org.junit.vintage",
          "module": "junit-vintage-engine",
          "excludes": [
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core"
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter"
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert"
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        },
        {
          "group": "org.springframework",
          "module": "spring-test"
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-test-2.3.1.RELEASE.jar",
          "size": 4781,
          "sha512": "3229b777e6f58698aa82a87a43723f72945a74ac4f094842489e2b14698552f1f10ba76f6e64d4547fb378015bb9be711ad7aff7b60a9ef1c783d90da2c670b4",
          "sha256": "04b6018b3f96ad8b4c080d08e648d155939c02b35191368f8e2ffda223c64ebe",
          "sha1": "aa800443c878a2ca6615cf13490286757195941c",
          "md5": "3c14cf85d42a17059bfd413351a617d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path"
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api"
        },
        {
          "group": "org.assertj",
          "module": "assertj-core"
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter"
        },
        {
          "group": "org.junit.vintage",
          "module": "junit-vintage-engine",
          "excludes": [
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core"
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter"
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert"
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        },
        {
          "group": "org.springframework",
          "module": "spring-test"
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-test-2.3.1.RELEASE.jar",
          "size": 4781,
          "sha512": "3229b777e6f58698aa82a87a43723f72945a74ac4f094842489e2b14698552f1f10ba76f6e64d4547fb378015bb9be711ad7aff7b60a9ef1c783d90da2c670b4",
          "sha256": "04b6018b3f96ad8b4c080d08e648d155939c02b35191368f8e2ffda223c64ebe",
          "sha1": "aa800443c878a2ca6615cf13490286757195941c",
          "md5": "3c14cf85d42a17059bfd413351a617d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-test-2.3.1.RELEASE-javadoc.jar",
          "size": 4781,
          "sha512": "2cdeb958e3de74740fe570d7ff03270a5219aee63e7f4e1a6ec6e39cc68f83471bd4bf2eb7f89f87d3aef3c4e261f607b00a939d350f919310d3ec9d6154b2fa",
          "sha256": "2ba275ea1293efe0d4fb7f5d1c13e3fc9e00b0371624cbb18512efc264c207d5",
          "sha1": "ed6d4808e6b69e7fbe546a75a47edda4d8ddb987",
          "md5": "dca97a86714004e5ff52cae0414d205c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-starter-test-2.3.1.RELEASE-sources.jar",
          "size": 4781,
          "sha512": "314e3b9c117f699f55efefc6f853773d3310aa6e09a6fd9b57d979436dcee5be8ac9c5e986a7f82b0d1c1b90b6b418d77a8bd3bd1cf27fdda5030591eef9b888",
          "sha256": "232dec8246fa202d107438ca4c5f30f0eb595eca78b89e9dd6a10a9286f6c85b",
          "sha1": "98e60377ef5f3fd18438fc0df66d29e1812e1e17",
          "md5": "cb5221d9a48b5e29d58f7822da8596ee"
        }
      ]
    }
  ]
}
