{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.3.1.RELEASE.jar",
          "url": "spring-boot-test-2.3.1.RELEASE.jar",
          "size": 214704,
          "sha512": "86bd0e5803c04bf23572ecb678d1a733c96f82f067adefa986d5de8281dd079c996423d3d6d6a10dd5f0499812cb34ea79b9bfcb74d3e0576450fae960b2e312",
          "sha256": "2c0fdf45f12170dbb15875ec38facf01d61dbb495da17f79160eb1cbfc5130f4",
          "sha1": "d103039c2def2b11fe55e6c362f7dd7b06e4d41b",
          "md5": "115b496c2c4f52de13b42be11c4876e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.3.1.RELEASE.jar",
          "url": "spring-boot-test-2.3.1.RELEASE.jar",
          "size": 214704,
          "sha512": "86bd0e5803c04bf23572ecb678d1a733c96f82f067adefa986d5de8281dd079c996423d3d6d6a10dd5f0499812cb34ea79b9bfcb74d3e0576450fae960b2e312",
          "sha256": "2c0fdf45f12170dbb15875ec38facf01d61dbb495da17f79160eb1cbfc5130f4",
          "sha1": "d103039c2def2b11fe55e6c362f7dd7b06e4d41b",
          "md5": "115b496c2c4f52de13b42be11c4876e3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-test-2.3.1.RELEASE-javadoc.jar",
          "size": 310328,
          "sha512": "977f44d76b4d4c77772e47cdf5e5311f0c5ad7842534b902f5568aed53113bd1b4f8bbd38c1f1eaf38c097c6d960336f5e2980ae5a2c5e2bc44627fb08f76ec5",
          "sha256": "0d121d169fe125b04e2432727c36daccb278f1a7fe11b86a5c01121db07ae85f",
          "sha1": "f15f2162d91e8a01265e944f18a9bcf910c7d3cc",
          "md5": "2eba2a5e15bff6e904ad7f1c24d7b4f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-test-2.3.1.RELEASE-sources.jar",
          "size": 148767,
          "sha512": "3833e4336ea12c8959d4783fc96f1374401c32d7983719af603ae424dfe87a940bfd6ba22e53642da1bd1f54a8d276fb39fcf9ae9b8e32daf0e5f4ef0ba1a82e",
          "sha256": "5cc88da8eab54951f7916f1467b88cbf6c63f0f2fb93d21b60e1aeddca074a77",
          "sha1": "2ed0c9c246f088f8296c2b59f68777ef9cbcc95b",
          "md5": "2fcf4fbd9a5d76637a97b1fd43856fd1"
        }
      ]
    }
  ]
}
