{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-parent",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress"
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.1.RELEASE.jar",
          "url": "spring-boot-loader-tools-2.3.1.RELEASE.jar",
          "size": 237757,
          "sha512": "4ed299952d29b441cc06c2b034ad53aa4d1788fcdabe0f18626b53898c6784f6317b634facc1f5a46503e7fa9ad9dd1da14f20cfc67b64efe70ecaf6244ed240",
          "sha256": "6f5fdcbee51aad8784f7c3f576ae75838434c1352be6fef5ae443c4056e2031f",
          "sha1": "4fde90e5b6bc6f8219860daa92ec297a47561fdc",
          "md5": "2692e4e7eea851c2e55d31efcde592a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-parent",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress"
        },
        {
          "group": "org.springframework",
          "module": "spring-core"
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.1.RELEASE.jar",
          "url": "spring-boot-loader-tools-2.3.1.RELEASE.jar",
          "size": 237757,
          "sha512": "4ed299952d29b441cc06c2b034ad53aa4d1788fcdabe0f18626b53898c6784f6317b634facc1f5a46503e7fa9ad9dd1da14f20cfc67b64efe70ecaf6244ed240",
          "sha256": "6f5fdcbee51aad8784f7c3f576ae75838434c1352be6fef5ae443c4056e2031f",
          "sha1": "4fde90e5b6bc6f8219860daa92ec297a47561fdc",
          "md5": "2692e4e7eea851c2e55d31efcde592a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-loader-tools-2.3.1.RELEASE-javadoc.jar",
          "size": 166996,
          "sha512": "5bc1ac1697434516adb3f2f7f57e0d8fcff5ab265312f375c087b8ea972f5392b0c500c4f4a0c8889fdd6d8e7146101503ed95c25b15d8781abf68591c7526c9",
          "sha256": "0c6a076d2b9c2a09c01502039874669aade36cc7dc0f09e9d7a4e1580ca0ca95",
          "sha1": "d96e0afe51980d05830394f6ef008865bfbefd04",
          "md5": "800164738e560f5e1db9887997e47b2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-loader-tools-2.3.1.RELEASE-sources.jar",
          "size": 202966,
          "sha512": "1362d3cc17e8aae027cc89ddb2374736c418499f8c632a04701c0cd9d3462ee4f21d40ecd5508bb3bc84dbd98e2c821c397dc04e40ef91386ba474b4c08ac922",
          "sha256": "8225dd148f161655a744e27882be7add3ed58bd062027f3bda64799c406cbce3",
          "sha1": "f630096e59cd812dd1e7d180a83a67c4761894a5",
          "md5": "86d0bbacf9e61ba513b3caa090a4187e"
        }
      ]
    }
  ]
}
