{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.5.7.jar",
          "url": "spring-boot-test-2.5.7.jar",
          "size": 221054,
          "sha512": "31fae97863fcf7cffe2730a9182ee7d40a27116d447ad92309b5aacd92b69364c690892addd8bc131e8cc6d584be778e57c573e80b492b58fb9dd078803d7881",
          "sha256": "456ec8c6e542523c1c1553be8a415eac69e46f1a2fd90ab34a459e0a62d7e87b",
          "sha1": "de64608da11a201a5d6fde5ed84157cbadfe69a0",
          "md5": "e4c8b885ee124a81ad5dc317cbaaf6bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.5.7.jar",
          "url": "spring-boot-test-2.5.7.jar",
          "size": 221054,
          "sha512": "31fae97863fcf7cffe2730a9182ee7d40a27116d447ad92309b5aacd92b69364c690892addd8bc131e8cc6d584be778e57c573e80b492b58fb9dd078803d7881",
          "sha256": "456ec8c6e542523c1c1553be8a415eac69e46f1a2fd90ab34a459e0a62d7e87b",
          "sha1": "de64608da11a201a5d6fde5ed84157cbadfe69a0",
          "md5": "e4c8b885ee124a81ad5dc317cbaaf6bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.7-javadoc.jar",
          "url": "spring-boot-test-2.5.7-javadoc.jar",
          "size": 317560,
          "sha512": "fc6ede9e066f57a2ebb1a664eda14160d63c71f0620c83acad867472739ee79bdd867e9937f2dfaa08f2c08005ec89fe0392b7a69e665cbe8d4753ddbe1b8c93",
          "sha256": "9d268b8a0ceaa445b8bd931033b1791f6a158243c77aa92b0abdca4cd9f0591a",
          "sha1": "5e3387ebedd734de1c37df7e6b2ab0e7c82da8a4",
          "md5": "ac09ffdf1ebff29556f5a8732889a250"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.7-sources.jar",
          "url": "spring-boot-test-2.5.7-sources.jar",
          "size": 153820,
          "sha512": "9af219d7c94dd8a8f634240cf6f9ab4911633fe477c1ae87843e89b09095be815bedd9c9bbbfb99de0d91436fc19ecbb2762d2a45be1dda8376556bc55a64a8d",
          "sha256": "37b3c8f8f73e9c3b6c7436f23d58de04c1654eda32fa4aa91c50f9a717f2df5d",
          "sha1": "04a4a66e08ba1b06dc8dda78c6f3bafb76679fde",
          "md5": "d7769ebf67548fbfcaa7b19c74bb0a48"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.7.jar",
          "url": "spring-boot-test-2.5.7.jar",
          "size": 221054,
          "sha512": "31fae97863fcf7cffe2730a9182ee7d40a27116d447ad92309b5aacd92b69364c690892addd8bc131e8cc6d584be778e57c573e80b492b58fb9dd078803d7881",
          "sha256": "456ec8c6e542523c1c1553be8a415eac69e46f1a2fd90ab34a459e0a62d7e87b",
          "sha1": "de64608da11a201a5d6fde5ed84157cbadfe69a0",
          "md5": "e4c8b885ee124a81ad5dc317cbaaf6bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.7.jar",
          "url": "spring-boot-test-2.5.7.jar",
          "size": 221054,
          "sha512": "31fae97863fcf7cffe2730a9182ee7d40a27116d447ad92309b5aacd92b69364c690892addd8bc131e8cc6d584be778e57c573e80b492b58fb9dd078803d7881",
          "sha256": "456ec8c6e542523c1c1553be8a415eac69e46f1a2fd90ab34a459e0a62d7e87b",
          "sha1": "de64608da11a201a5d6fde5ed84157cbadfe69a0",
          "md5": "e4c8b885ee124a81ad5dc317cbaaf6bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.5.7"
        }
      ]
    }
  ]
}
