{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-tx",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-5.3.13.jar",
          "url": "spring-tx-5.3.13.jar",
          "size": 333422,
          "sha512": "40ca8a5d4cc45b87c2d61ac1344f26ae9367ce1e599d09524dcdc8d0000ee11ebc15c657602d11352e1cf0f752408d06ef4e153b725858da2b238b39eeb4eb69",
          "sha256": "492bf11ca5a96fb2f12c39a6ba6b2157f192907587ef51a38f683237cb0f7e2e",
          "sha1": "4b7346f190d6a6f4b983bc23d1f0145c2ff2dbb7",
          "md5": "d281e305a04dedf99c98302a05dc5a7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-tx-5.3.13.jar",
          "url": "spring-tx-5.3.13.jar",
          "size": 333422,
          "sha512": "40ca8a5d4cc45b87c2d61ac1344f26ae9367ce1e599d09524dcdc8d0000ee11ebc15c657602d11352e1cf0f752408d06ef4e153b725858da2b238b39eeb4eb69",
          "sha256": "492bf11ca5a96fb2f12c39a6ba6b2157f192907587ef51a38f683237cb0f7e2e",
          "sha1": "4b7346f190d6a6f4b983bc23d1f0145c2ff2dbb7",
          "md5": "d281e305a04dedf99c98302a05dc5a7d"
        }
      ]
    }
  ]
}
