{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-reactor-netty",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "size": 4778,
          "sha512": "92477562bb39dc139c22ffdce13bd495e033cb6bb55998ce5ab3dec99dd919596406a3729df20f21e44fc4ede94c8d17cb8683f64a2e2dbe14002d81fe9d6854",
          "sha256": "c33df77f7069a8409e629e572c48d8138d33f0c5f736b557d716db98afde8a31",
          "sha1": "25558dbe712bec74884b845cb3d00150ea6f97b9",
          "md5": "96b0c7a3210b6cb733c91d1773973f81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "size": 4778,
          "sha512": "92477562bb39dc139c22ffdce13bd495e033cb6bb55998ce5ab3dec99dd919596406a3729df20f21e44fc4ede94c8d17cb8683f64a2e2dbe14002d81fe9d6854",
          "sha256": "c33df77f7069a8409e629e572c48d8138d33f0c5f736b557d716db98afde8a31",
          "sha1": "25558dbe712bec74884b845cb3d00150ea6f97b9",
          "md5": "96b0c7a3210b6cb733c91d1773973f81"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "size": 4778,
          "sha512": "92477562bb39dc139c22ffdce13bd495e033cb6bb55998ce5ab3dec99dd919596406a3729df20f21e44fc4ede94c8d17cb8683f64a2e2dbe14002d81fe9d6854",
          "sha256": "c33df77f7069a8409e629e572c48d8138d33f0c5f736b557d716db98afde8a31",
          "sha1": "25558dbe712bec74884b845cb3d00150ea6f97b9",
          "md5": "96b0c7a3210b6cb733c91d1773973f81"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-reactor-netty-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7.jar",
          "size": 4778,
          "sha512": "92477562bb39dc139c22ffdce13bd495e033cb6bb55998ce5ab3dec99dd919596406a3729df20f21e44fc4ede94c8d17cb8683f64a2e2dbe14002d81fe9d6854",
          "sha256": "c33df77f7069a8409e629e572c48d8138d33f0c5f736b557d716db98afde8a31",
          "sha1": "25558dbe712bec74884b845cb3d00150ea6f97b9",
          "md5": "96b0c7a3210b6cb733c91d1773973f81"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-reactor-netty-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7-javadoc.jar",
          "size": 4752,
          "sha512": "122ac0ecf2c5490b36d00cd076ab481a69d0c9c2f94b4ecd10cc95404a69307c05aa255d8933c309ae7a7f636b4a53aab01fafbb6589b2c4ee250cfe84d46602",
          "sha256": "b2b3fe4da25028829cff961497fce37a1cc4acfe3c14ca209e0190948f807fc7",
          "sha1": "622e1535d6d5e174cc8e5d3ab0c0f48f0cca7477",
          "md5": "71bed0ae93981924aeb2b9fdd62837d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-reactor-netty-2.5.7-sources.jar",
          "url": "spring-boot-starter-reactor-netty-2.5.7-sources.jar",
          "size": 4751,
          "sha512": "771594813fbb369a4e3fe32666cc4017ec3d215804c5b1c87464c935dc480e239e17a31092593863cd41e2147038557d09e278038401b3dc5c0f059f3420ff6f",
          "sha256": "ed0f0e7748b1a0acbc423c5eaa6138617a2d32c07bea5b9b6fba97f138bf66b3",
          "sha1": "1480b376d9e462bc3a49431902e1002e69759f75",
          "md5": "237f10e8ed9b659b2dda6a7552feee0b"
        }
      ]
    }
  ]
}
