{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.13.jar",
          "url": "spring-expression-5.3.13.jar",
          "size": 288700,
          "sha512": "6a706bc33a9d9690f7b48abadcde0bd91f4ac5d88cc7ca787cb4e569050ea6ba30ac34bda456f2416cedf89eeac23ee01b8f57dc45c13a39e1b8958b3a10aa88",
          "sha256": "53b006b299f4d9788a156a1f4a85b6cabcc85d53c5bad1436b8a136ee44dbfeb",
          "sha1": "8f7448f4fb296a92855fd0afea3375ce41061e84",
          "md5": "ee55ec486e6117774aa459e96530e5be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.13.jar",
          "url": "spring-expression-5.3.13.jar",
          "size": 288700,
          "sha512": "6a706bc33a9d9690f7b48abadcde0bd91f4ac5d88cc7ca787cb4e569050ea6ba30ac34bda456f2416cedf89eeac23ee01b8f57dc45c13a39e1b8958b3a10aa88",
          "sha256": "53b006b299f4d9788a156a1f4a85b6cabcc85d53c5bad1436b8a136ee44dbfeb",
          "sha1": "8f7448f4fb296a92855fd0afea3375ce41061e84",
          "md5": "ee55ec486e6117774aa459e96530e5be"
        }
      ]
    }
  ]
}
