{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el"
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-validation-2.3.1.RELEASE.jar",
          "size": 4757,
          "sha512": "effc881966733dd4597501d70c1d86fcec15a60a26944cd96d804a64ac3a0b59891243c7eea48622ad3fdec2992373d533716c0e41043fa3ad35efd984cb7de6",
          "sha256": "be42ee021d96da12d3ca63df516d78ea113a8eff2b59f11b92e2e5c2ebcbc317",
          "sha1": "ec99ba85f02b2bec42b84c9c5e74d035ec61109a",
          "md5": "7738a27cbf5ecabf6f735f97811c6f97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el"
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-validation-2.3.1.RELEASE.jar",
          "size": 4757,
          "sha512": "effc881966733dd4597501d70c1d86fcec15a60a26944cd96d804a64ac3a0b59891243c7eea48622ad3fdec2992373d533716c0e41043fa3ad35efd984cb7de6",
          "sha256": "be42ee021d96da12d3ca63df516d78ea113a8eff2b59f11b92e2e5c2ebcbc317",
          "sha1": "ec99ba85f02b2bec42b84c9c5e74d035ec61109a",
          "md5": "7738a27cbf5ecabf6f735f97811c6f97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-validation-2.3.1.RELEASE-javadoc.jar",
          "size": 4757,
          "sha512": "fc820b8c2c1a0b5a092871ddb7cbafad460126ae30247a63bb28c602749a28ff5703bebd1a8be76780807ac6aba64ade3dfdc1da6ce557dd36e224cdeb8ba75e",
          "sha256": "c2f64da55e08db5766664c73664304ba3317bd93a9c532fe7e011b41faf98d26",
          "sha1": "243743f114f531c3bfb646cbbed6fedeae883abd",
          "md5": "898b8b1c42e0985492402867bac3c8e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-starter-validation-2.3.1.RELEASE-sources.jar",
          "size": 4757,
          "sha512": "f46b72a0f95459b914253b9ae763451ba4f61d099f1f10ff575cc7af9567325bd2508ae16ce6ddd3526375c80db3a78650905e5b3b908c1425147ca946a009da",
          "sha256": "5c051f11eb33be7bd1d50aff85647c55473ea9606e0783b13931b5028bd290ec",
          "sha1": "5f1ca0aa98451649120623a5a9a7d66db427627c",
          "md5": "861ee377beb1d6f342085f22e7dd3428"
        }
      ]
    }
  ]
}
