{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc"
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-web-2.3.1.RELEASE.jar",
          "size": 4796,
          "sha512": "9e168c34732b844d1d1e93a6cf95202de320d0ff2cb6642449e131dae6b1b1df401829dd9a903cbca2510ee2be2969b8958c10524e006fc5217e162acd1f0796",
          "sha256": "e57befd685f89aed426760d0a3a336e8585cabd86410e06830bff753d309e6e1",
          "sha1": "555c4f90141cdbc7637145e413bca0d622ba6796",
          "md5": "53473c51ff755ebc4ac7c2f24b0b3eca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.3.1.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web"
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc"
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-web-2.3.1.RELEASE.jar",
          "size": 4796,
          "sha512": "9e168c34732b844d1d1e93a6cf95202de320d0ff2cb6642449e131dae6b1b1df401829dd9a903cbca2510ee2be2969b8958c10524e006fc5217e162acd1f0796",
          "sha256": "e57befd685f89aed426760d0a3a336e8585cabd86410e06830bff753d309e6e1",
          "sha1": "555c4f90141cdbc7637145e413bca0d622ba6796",
          "md5": "53473c51ff755ebc4ac7c2f24b0b3eca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-web-2.3.1.RELEASE-javadoc.jar",
          "size": 4796,
          "sha512": "9e168c34732b844d1d1e93a6cf95202de320d0ff2cb6642449e131dae6b1b1df401829dd9a903cbca2510ee2be2969b8958c10524e006fc5217e162acd1f0796",
          "sha256": "e57befd685f89aed426760d0a3a336e8585cabd86410e06830bff753d309e6e1",
          "sha1": "555c4f90141cdbc7637145e413bca0d622ba6796",
          "md5": "53473c51ff755ebc4ac7c2f24b0b3eca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-starter-web-2.3.1.RELEASE-sources.jar",
          "size": 4796,
          "sha512": "4e8762c36765bb7b106c92315dbf188f9fbac2848f3979baf0f73a50bcc4c5865c17184a8fd1f36b3b59025f52e52d3e7709b69d2c746697a294842a9206a263",
          "sha256": "3bcdcc2fcb66f4eaf75b0acaaa4e6f88658efe420be5bcd4de9366c1d44b4ae7",
          "sha1": "e2f5b1be98ea94fb9cfb69de24ea6520ccc05acb",
          "md5": "c9f9e9fb313697c614739e3d2dff3775"
        }
      ]
    }
  ]
}
