{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.integration",
    "module": "spring-integration-core",
    "version": "5.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "f2obtkxawbd6jbeh6jzeurvjbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "1.2.5.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.3.6.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.2.7.RELEASE"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "1.2.5.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.3.6.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE-javadoc.jar",
          "url": "spring-integration-core-5.3.1.RELEASE-javadoc.jar",
          "size": 3237096,
          "sha512": "fa772f4a5250fe6e57e79bfe122c18bc5140855fbe2297a987727099a0f7f1470f38ed3a83fa0518fd405798492dd1c0a8c0c5329b68fa7b1c63a335ef06f47b",
          "sha256": "d02c4421e1d248a7142b7a6cc772e6fef7f647a9ca75079ae3fd7c012fd45ca2",
          "sha1": "1d70625c4754be2ebe577aae80ba59e0179d2dc3",
          "md5": "6b533e2e883b59c656aade0aaaa8c422"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE-sources.jar",
          "url": "spring-integration-core-5.3.1.RELEASE-sources.jar",
          "size": 1198706,
          "sha512": "c4c2454d00c6f0e2dea623c6be002bdad11f940f844e62b9c0105d9fe018bfa2dcc350d8dfeca272d9f8524bb2fabdbb2fee036fa18942d2a4ff5b49f67fca5a",
          "sha256": "1b4dac86f15e399d7ca8c6a4ed557a43c1c54422a386c40ccdcae614726b7f1c",
          "sha1": "6e196df00f0f5466cbafbe1adb9e9d0d2a55ca41",
          "md5": "a4acc6cfe681f0e1fb693379d87b82c3"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.esotericsoftware",
          "module": "kryo-shaded",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.avro",
          "module": "avro",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-optional",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.esotericsoftware",
          "module": "kryo-shaded",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-ratelimiter",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.avro",
          "module": "avro",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-optional",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "providedApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-provided",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "providedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-core-5.3.1.RELEASE.jar",
          "url": "spring-integration-core-5.3.1.RELEASE.jar",
          "size": 1576068,
          "sha512": "046fb8178650ded59ce8eea944d6fd4ce08cc089deaf215f9bbd22db36a957f90eb2c0a13a1d1ba9cda64cbc41d0c31de3c09b3f64cb583023edec131540a899",
          "sha256": "287f5008bec7776c8482882a970b4a434ad8154c22ec89acbfdd27c9ca88eb11",
          "sha1": "5a989a1a4973c234ca64396cb212070ce425066c",
          "md5": "0d7f221fe33ebf3459fe1bd50a0dc89b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-core-provided",
          "version": "5.3.1.RELEASE"
        }
      ]
    }
  ]
}
