{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.integration",
    "module": "spring-integration-jmx",
    "version": "5.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "f2obtkxawbd6jbeh6jzeurvjbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.integration",
          "module": "spring-integration-core",
          "version": {
            "requires": "5.3.1.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.integration",
          "module": "spring-integration-core",
          "version": {
            "requires": "5.3.1.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE-javadoc.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE-javadoc.jar",
          "size": 128635,
          "sha512": "94eff8459056601cba0fd186009c056fe5c1c3dd9b2651226cafd0d711ea69970ee74bd419ca938810b048c300f58e556871f3dbd87fcdeb6ee567a21b909347",
          "sha256": "c6db30ad80303a8bc2f90ef7796abb4de8e7862727006f0728c181a5101d38ac",
          "sha1": "1eef6d94840ed3f13686d7849f7dd1f21289fb7f",
          "md5": "a439b422f0742ad634b25a057ed45ca2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE-sources.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE-sources.jar",
          "size": 55835,
          "sha512": "b75375eb710b867a5a6aa5342da72a23538adc3983836f358798dcb7141f1d40c20a2b94371966422746a9d964801486373a3cab31e0f15d5926218fb6f75c79",
          "sha256": "9dc830de6e2f8baa68fa1c934fd9e4cf08e9e3223037f6eca1f45f20a06cd6aa",
          "sha1": "3937f4499a541f18bbf7f1e22bb3006987781d5f",
          "md5": "1c6167656f2bc3e3be71e37a524b4dbc"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-jmx-optional",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-jmx-optional",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "providedApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-jmx-provided",
          "version": "5.3.1.RELEASE"
        }
      ]
    },
    {
      "name": "providedRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "url": "spring-integration-jmx-5.3.1.RELEASE.jar",
          "size": 71030,
          "sha512": "1dc604c82d2bfab20b9dcdcd5e176f9c430deeffef1070c75da45a8c4bd2f2b8e99ef3483c99acdd0251a876dcdd12ce42abc6cc7cfb08709d19f2760b98aa0c",
          "sha256": "9f091c5a46d596d95b9ca8c3e8cdffe4245aee87756e20b7dba458c9ec533d62",
          "sha1": "4c037f4e82eceb1fa3dfc7c708126e2843402268",
          "md5": "2dc1b6e2110c3528b1934a589f7b0bab"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.integration",
          "name": "spring-integration-jmx-provided",
          "version": "5.3.1.RELEASE"
        }
      ]
    }
  ]
}
