{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7.jar",
          "url": "spring-boot-starter-webflux-2.5.7.jar",
          "size": 4788,
          "sha512": "eedecefff9441c9abf2d92383c8f09bf2cc3cd1d585e376c8d979fb77e878d2894e1007f3980471fd102302278ffd042528f5d0de2b0d6bb4851ffe3cae1b79c",
          "sha256": "e8d5192d9992cae1da8f2e4fe7dde98b9432d79feb378e739c7237720aff8069",
          "sha1": "1b207fbc6bc483876671f65bf8a1dc5142da447b",
          "md5": "5fafa32f09177b68a249149ed515c277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7.jar",
          "url": "spring-boot-starter-webflux-2.5.7.jar",
          "size": 4788,
          "sha512": "eedecefff9441c9abf2d92383c8f09bf2cc3cd1d585e376c8d979fb77e878d2894e1007f3980471fd102302278ffd042528f5d0de2b0d6bb4851ffe3cae1b79c",
          "sha256": "e8d5192d9992cae1da8f2e4fe7dde98b9432d79feb378e739c7237720aff8069",
          "sha1": "1b207fbc6bc483876671f65bf8a1dc5142da447b",
          "md5": "5fafa32f09177b68a249149ed515c277"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7.jar",
          "url": "spring-boot-starter-webflux-2.5.7.jar",
          "size": 4788,
          "sha512": "eedecefff9441c9abf2d92383c8f09bf2cc3cd1d585e376c8d979fb77e878d2894e1007f3980471fd102302278ffd042528f5d0de2b0d6bb4851ffe3cae1b79c",
          "sha256": "e8d5192d9992cae1da8f2e4fe7dde98b9432d79feb378e739c7237720aff8069",
          "sha1": "1b207fbc6bc483876671f65bf8a1dc5142da447b",
          "md5": "5fafa32f09177b68a249149ed515c277"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-webflux-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7.jar",
          "url": "spring-boot-starter-webflux-2.5.7.jar",
          "size": 4788,
          "sha512": "eedecefff9441c9abf2d92383c8f09bf2cc3cd1d585e376c8d979fb77e878d2894e1007f3980471fd102302278ffd042528f5d0de2b0d6bb4851ffe3cae1b79c",
          "sha256": "e8d5192d9992cae1da8f2e4fe7dde98b9432d79feb378e739c7237720aff8069",
          "sha1": "1b207fbc6bc483876671f65bf8a1dc5142da447b",
          "md5": "5fafa32f09177b68a249149ed515c277"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-webflux-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-webflux-2.5.7-javadoc.jar",
          "size": 4748,
          "sha512": "0b2e1d93594c3a89056f03960bdc9dcbc2fb1a1b524d9c71ec99bf4bdd9c0b123999a8709ab0a39acb7cc6e54d1f2b4b8dc9d6ab8e8e4d1fa5ab8ca7978955d3",
          "sha256": "75cc92c16bbfdb4d233f111f073d01c76f52c5cbafab2aa91335657e179babe2",
          "sha1": "a822eb30bd302b17045e0b44f0de1c710dbb8a01",
          "md5": "2c956ec966f9b329df7928d33a582747"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-2.5.7-sources.jar",
          "url": "spring-boot-starter-webflux-2.5.7-sources.jar",
          "size": 4746,
          "sha512": "3235765bfa46424d773b032fda755850b6fb38bbbb3f819e296ffc20cd7d68f9ded35b7a4ecb71884e353278d371a6d9f085ac34f17fe3ca64c2a93384668969",
          "sha256": "18c57f8bea8b6cf39fc3f4c525b4891bd44de1fddc0a4705d5b25bd7e8f9f8b8",
          "sha1": "a38ac30a38b4b6a1f9a30d0cb5d4cba5042ab8d0",
          "md5": "11f2de45effb6a63ddbdaec74f28296e"
        }
      ]
    }
  ]
}
