{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.13.jar",
          "url": "spring-test-5.3.13.jar",
          "size": 786745,
          "sha512": "925cada03118d3a08992999826707b4ce1cda8d8a296c14df4db97aa15d351c591910691ee00001c01e308f92151d5d0deb297c6ad2b6cc5a3f04058ec0bfe81",
          "sha256": "5ef4258236da3fa1f70febe4e2c584cb9b22b4d69d3858c5c8c450da34b2a915",
          "sha1": "71d8c97d3f79e4399df223772190aaee19bbf197",
          "md5": "0db835968704b5d3c0211f8424b7d602"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.13.jar",
          "url": "spring-test-5.3.13.jar",
          "size": 786745,
          "sha512": "925cada03118d3a08992999826707b4ce1cda8d8a296c14df4db97aa15d351c591910691ee00001c01e308f92151d5d0deb297c6ad2b6cc5a3f04058ec0bfe81",
          "sha256": "5ef4258236da3fa1f70febe4e2c584cb9b22b4d69d3858c5c8c450da34b2a915",
          "sha1": "71d8c97d3f79e4399df223772190aaee19bbf197",
          "md5": "0db835968704b5d3c0211f8424b7d602"
        }
      ]
    }
  ]
}
