{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.5.7.jar",
          "url": "spring-boot-starter-2.5.7.jar",
          "size": 4771,
          "sha512": "f81582a6f92e08c3f0c2a23fa227ec81b76791d89a57719b437962c6e6d79113d16c8637b73f3669f95da839b342c13f7f4206f4831e1fc61572ebed01c97059",
          "sha256": "f1ad60f2d9f5213d4fc64f6cb1c49676dff1845db9f4fadfa7a7ea02e82ff7d0",
          "sha1": "cc377ad9f75def23610d386e5792666e3d88c20c",
          "md5": "0b36d151ebfc5702a3dae49ccbaad3df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.5.7.jar",
          "url": "spring-boot-starter-2.5.7.jar",
          "size": 4771,
          "sha512": "f81582a6f92e08c3f0c2a23fa227ec81b76791d89a57719b437962c6e6d79113d16c8637b73f3669f95da839b342c13f7f4206f4831e1fc61572ebed01c97059",
          "sha256": "f1ad60f2d9f5213d4fc64f6cb1c49676dff1845db9f4fadfa7a7ea02e82ff7d0",
          "sha1": "cc377ad9f75def23610d386e5792666e3d88c20c",
          "md5": "0b36d151ebfc5702a3dae49ccbaad3df"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.7.jar",
          "url": "spring-boot-starter-2.5.7.jar",
          "size": 4771,
          "sha512": "f81582a6f92e08c3f0c2a23fa227ec81b76791d89a57719b437962c6e6d79113d16c8637b73f3669f95da839b342c13f7f4206f4831e1fc61572ebed01c97059",
          "sha256": "f1ad60f2d9f5213d4fc64f6cb1c49676dff1845db9f4fadfa7a7ea02e82ff7d0",
          "sha1": "cc377ad9f75def23610d386e5792666e3d88c20c",
          "md5": "0b36d151ebfc5702a3dae49ccbaad3df"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.7.jar",
          "url": "spring-boot-starter-2.5.7.jar",
          "size": 4771,
          "sha512": "f81582a6f92e08c3f0c2a23fa227ec81b76791d89a57719b437962c6e6d79113d16c8637b73f3669f95da839b342c13f7f4206f4831e1fc61572ebed01c97059",
          "sha256": "f1ad60f2d9f5213d4fc64f6cb1c49676dff1845db9f4fadfa7a7ea02e82ff7d0",
          "sha1": "cc377ad9f75def23610d386e5792666e3d88c20c",
          "md5": "0b36d151ebfc5702a3dae49ccbaad3df"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-2.5.7-javadoc.jar",
          "size": 4739,
          "sha512": "6b3ba468253dc7ddb724486d23bd5f2b38c22e75f9e1467295de0f26af3869a9ab85fed56fd1818abee36a02a57917f40f632336bbdf3f5b8a19503c3b152ce4",
          "sha256": "e6d194e513d46b110dbecb7b42fe6ca236d9a4cf9916a63a09a43d87471be060",
          "sha1": "925b9d97e946fdd4be9f06605265cb31ebb8d52f",
          "md5": "413ba96db85763d8fe483a8e5a3f73dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.7-sources.jar",
          "url": "spring-boot-starter-2.5.7-sources.jar",
          "size": 4738,
          "sha512": "f3de9453e8926c28cb3ed9377ea7d82c09914b53dd6744ffc4856e0f8819d0780cf1dd7b70a1f2f38b6916a3b04a00811ef36a6df94e165320bc92b8dcdbc365",
          "sha256": "8d89d7a873d6785eadab68bfeeaf77b94c4f1b820328dabb8af9c57edd42b990",
          "sha1": "f2dad7b1c27d4f8bc38ac30d27ea19f47c327813",
          "md5": "ce33526a5290cdd12a03712c82d1e2a1"
        }
      ]
    }
  ]
}
