{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.7.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7.jar",
          "url": "spring-boot-starter-actuator-2.5.7.jar",
          "size": 4808,
          "sha512": "caf3d7309ccd48b6ab6c607c1a4047aea817e41b35fbc5764da482064a3dc0debf08387d2fe9e99d076654efcf705aea54c63f38183a3b4269a3ad5807af9d1f",
          "sha256": "e3c08c32913cda0819d14b50176527eb8667ab6e34f930e2e3d5742251af7c8d",
          "sha1": "f8497db9a5930dda1262f23cf2ed8a57b64a3300",
          "md5": "eb4e3a93985022d9b9b72d7eeaaf5512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.7.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7.jar",
          "url": "spring-boot-starter-actuator-2.5.7.jar",
          "size": 4808,
          "sha512": "caf3d7309ccd48b6ab6c607c1a4047aea817e41b35fbc5764da482064a3dc0debf08387d2fe9e99d076654efcf705aea54c63f38183a3b4269a3ad5807af9d1f",
          "sha256": "e3c08c32913cda0819d14b50176527eb8667ab6e34f930e2e3d5742251af7c8d",
          "sha1": "f8497db9a5930dda1262f23cf2ed8a57b64a3300",
          "md5": "eb4e3a93985022d9b9b72d7eeaaf5512"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7.jar",
          "url": "spring-boot-starter-actuator-2.5.7.jar",
          "size": 4808,
          "sha512": "caf3d7309ccd48b6ab6c607c1a4047aea817e41b35fbc5764da482064a3dc0debf08387d2fe9e99d076654efcf705aea54c63f38183a3b4269a3ad5807af9d1f",
          "sha256": "e3c08c32913cda0819d14b50176527eb8667ab6e34f930e2e3d5742251af7c8d",
          "sha1": "f8497db9a5930dda1262f23cf2ed8a57b64a3300",
          "md5": "eb4e3a93985022d9b9b72d7eeaaf5512"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7.jar",
          "url": "spring-boot-starter-actuator-2.5.7.jar",
          "size": 4808,
          "sha512": "caf3d7309ccd48b6ab6c607c1a4047aea817e41b35fbc5764da482064a3dc0debf08387d2fe9e99d076654efcf705aea54c63f38183a3b4269a3ad5807af9d1f",
          "sha256": "e3c08c32913cda0819d14b50176527eb8667ab6e34f930e2e3d5742251af7c8d",
          "sha1": "f8497db9a5930dda1262f23cf2ed8a57b64a3300",
          "md5": "eb4e3a93985022d9b9b72d7eeaaf5512"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-actuator-2.5.7-javadoc.jar",
          "size": 4748,
          "sha512": "5c038a1222c49d72ac19f3bb38b0c2e88d2b93390b266360d3f6099bf54bc02af19cdfcd4e73aaabd6b770247625f1ce4944e051e79ed6d61f0aaf2467a0395d",
          "sha256": "92543ea74452248a5c954d9e40d99968a571076b8a4af00ebfe83c2b25ee0c03",
          "sha1": "1dc6d07569e2972704ced472cc1b64781a4e7027",
          "md5": "493b6e8c27fb5500fce08bd1acf2706f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-2.5.7-sources.jar",
          "url": "spring-boot-starter-actuator-2.5.7-sources.jar",
          "size": 4746,
          "sha512": "e76500769baece68a9ca0ed2ba98f58485dc7cb4d69db2afade9a8b377d1cc8d29887c3ad19c57d18604c5acccdc3717928a01d2ce535420b338d65997ab9383",
          "sha256": "7911392f1e7bc51aa72ce5a2b58f5d52ca27db58e74df82ed38091a370bd4aa8",
          "sha1": "51c63cdcb14aeba6ccaa5f0bc447ec8ebd47089d",
          "md5": "d442930fd95159780f9ba20ced6367fc"
        }
      ]
    }
  ]
}
