{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-parent",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.vaadin.external.google",
          "module": "android-json",
          "version": {
            "requires": "0.0.20131108.vaadin1"
          }
        },
        {
          "group": "commons-fileupload",
          "module": "commons-fileupload",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.spring.asciidoctor",
          "module": "spring-asciidoctor-extensions-block-switch",
          "version": {
            "requires": "0.4.3.RELEASE"
          }
        },
        {
          "group": "io.spring.asciidoctor",
          "module": "spring-asciidoctor-extensions-spring-boot",
          "version": {
            "requires": "0.4.3.RELEASE"
          }
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.11"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-settings-builder",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-file",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.plugin-tools",
          "module": "maven-plugin-annotations",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.maven.plugins",
          "module": "maven-shade-plugin",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.apache.maven.shared",
          "module": "maven-common-artifact-filters",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.apache.maven.shared",
          "module": "maven-invoker",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.sonatype.plexus",
          "module": "plexus-build-api",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.sonatype.plexus",
          "module": "plexus-sec-dispatcher",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.sonatype.sisu",
          "module": "sisu-inject-plexus",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.spockframework",
          "module": "spock-core",
          "version": {
            "requires": "1.3-groovy-2.5"
          }
        },
        {
          "group": "org.spockframework",
          "module": "spock-spring",
          "version": {
            "requires": "1.3-groovy-2.5"
          }
        },
        {
          "group": "org.testng",
          "module": "testng",
          "version": {
            "requires": "6.14.3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.vaadin.external.google",
          "module": "android-json",
          "version": {
            "requires": "0.0.20131108.vaadin1"
          }
        },
        {
          "group": "commons-fileupload",
          "module": "commons-fileupload",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.mockk",
          "module": "mockk",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "io.spring.asciidoctor",
          "module": "spring-asciidoctor-extensions-block-switch",
          "version": {
            "requires": "0.4.3.RELEASE"
          }
        },
        {
          "group": "io.spring.asciidoctor",
          "module": "spring-asciidoctor-extensions-spring-boot",
          "version": {
            "requires": "0.4.3.RELEASE"
          }
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.11"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-settings-builder",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-file",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.apache.maven.plugin-tools",
          "module": "maven-plugin-annotations",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.maven.plugins",
          "module": "maven-shade-plugin",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.apache.maven.shared",
          "module": "maven-common-artifact-filters",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.apache.maven.shared",
          "module": "maven-invoker",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.sonatype.plexus",
          "module": "plexus-build-api",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.sonatype.plexus",
          "module": "plexus-sec-dispatcher",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.sonatype.sisu",
          "module": "sisu-inject-plexus",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.spockframework",
          "module": "spock-core",
          "version": {
            "requires": "1.3-groovy-2.5"
          }
        },
        {
          "group": "org.spockframework",
          "module": "spock-spring",
          "version": {
            "requires": "1.3-groovy-2.5"
          }
        },
        {
          "group": "org.testng",
          "module": "testng",
          "version": {
            "requires": "6.14.3"
          }
        }
      ]
    }
  ]
}
