{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7.jar",
          "url": "spring-boot-actuator-2.5.7.jar",
          "size": 646453,
          "sha512": "419123172cf0264a71850272d339fe1cb7b3a726d44eba46a518a4499b019e428d3db9ce1c4f091653bf9a8b7d17dddca29a07cb902e2fec76c5f4f9182cbfae",
          "sha256": "058f4ac675391245a83918aa8de57fe3b88f02bf900d7d3d108e40d97de4c947",
          "sha1": "9e968a1b0661f136cc2400c5ff8e6a5b4e0c3e44",
          "md5": "6508994a1313c73787cca720af4e7ed5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7.jar",
          "url": "spring-boot-actuator-2.5.7.jar",
          "size": 646453,
          "sha512": "419123172cf0264a71850272d339fe1cb7b3a726d44eba46a518a4499b019e428d3db9ce1c4f091653bf9a8b7d17dddca29a07cb902e2fec76c5f4f9182cbfae",
          "sha256": "058f4ac675391245a83918aa8de57fe3b88f02bf900d7d3d108e40d97de4c947",
          "sha1": "9e968a1b0661f136cc2400c5ff8e6a5b4e0c3e44",
          "md5": "6508994a1313c73787cca720af4e7ed5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7-javadoc.jar",
          "url": "spring-boot-actuator-2.5.7-javadoc.jar",
          "size": 1349128,
          "sha512": "2c92c8e0e2ec44189d9b0a97e24f953ef3d036ad7b82e1d67fdc1e6d1d260a2f475c16caf69bf84d7b18ccbc5dd784a677d51aeed951854664afc652d8c3aee3",
          "sha256": "cee37350b8215e581e1449509962f468945ff81bee0f47128b9f86a8f17dfd0e",
          "sha1": "1f58271d3813a451b874cc3a5f545da23ea6cd61",
          "md5": "7fe9530e1889a25281bf773814b2e212"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7-sources.jar",
          "url": "spring-boot-actuator-2.5.7-sources.jar",
          "size": 450544,
          "sha512": "35cc2152c34c0057efdcc6ae847122e906edb45ba59677b0b207308ddf4ece555f0e8dfdaacc355d33826cd937bd9ff73fdc4bb544dda066c81b3e82401fa08b",
          "sha256": "7e2636a36857ad17c4d0fabe67ccf3f1b7df11e9f7b0504c037a67ccbff9f784",
          "sha1": "934a960810e0f172ccf2065304da63e8884a7613",
          "md5": "0b8ad7ca6b778f1e5327e2a834192e0a"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7.jar",
          "url": "spring-boot-actuator-2.5.7.jar",
          "size": 646453,
          "sha512": "419123172cf0264a71850272d339fe1cb7b3a726d44eba46a518a4499b019e428d3db9ce1c4f091653bf9a8b7d17dddca29a07cb902e2fec76c5f4f9182cbfae",
          "sha256": "058f4ac675391245a83918aa8de57fe3b88f02bf900d7d3d108e40d97de4c947",
          "sha1": "9e968a1b0661f136cc2400c5ff8e6a5b4e0c3e44",
          "md5": "6508994a1313c73787cca720af4e7ed5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-2.5.7.jar",
          "url": "spring-boot-actuator-2.5.7.jar",
          "size": 646453,
          "sha512": "419123172cf0264a71850272d339fe1cb7b3a726d44eba46a518a4499b019e428d3db9ce1c4f091653bf9a8b7d17dddca29a07cb902e2fec76c5f4f9182cbfae",
          "sha256": "058f4ac675391245a83918aa8de57fe3b88f02bf900d7d3d108e40d97de4c947",
          "sha1": "9e968a1b0661f136cc2400c5ff8e6a5b4e0c3e44",
          "md5": "6508994a1313c73787cca720af4e7ed5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-maven-optional",
          "version": "2.5.7"
        }
      ]
    }
  ]
}
