{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.3.1.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "ilp2nxb3vvdvjnj6fv6xf32egy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el"
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.1.RELEASE.jar",
          "size": 4789,
          "sha512": "d5d22c0f665534e45ecc9bb74fb54e4ac79fc7b45d2446b560ad17c17a827933d6782aa8e0fefaf0ee4c3ad21d59ac7f0e7cec870f1d4fa57e14994542039c7e",
          "sha256": "24789d7c76ee2b54cd8393e524af5e0e9580d303a9f4a565923fda893e3e49c4",
          "sha1": "5b599d0da04e724479c22daa47f9bfd62533a2e9",
          "md5": "5bc0e688d3a1a954d479aca239644f6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el"
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.1.RELEASE.jar",
          "url": "spring-boot-starter-tomcat-2.3.1.RELEASE.jar",
          "size": 4789,
          "sha512": "d5d22c0f665534e45ecc9bb74fb54e4ac79fc7b45d2446b560ad17c17a827933d6782aa8e0fefaf0ee4c3ad21d59ac7f0e7cec870f1d4fa57e14994542039c7e",
          "sha256": "24789d7c76ee2b54cd8393e524af5e0e9580d303a9f4a565923fda893e3e49c4",
          "sha1": "5b599d0da04e724479c22daa47f9bfd62533a2e9",
          "md5": "5bc0e688d3a1a954d479aca239644f6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.1.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.3.1.RELEASE-javadoc.jar",
          "size": 4789,
          "sha512": "d5d22c0f665534e45ecc9bb74fb54e4ac79fc7b45d2446b560ad17c17a827933d6782aa8e0fefaf0ee4c3ad21d59ac7f0e7cec870f1d4fa57e14994542039c7e",
          "sha256": "24789d7c76ee2b54cd8393e524af5e0e9580d303a9f4a565923fda893e3e49c4",
          "sha1": "5b599d0da04e724479c22daa47f9bfd62533a2e9",
          "md5": "5bc0e688d3a1a954d479aca239644f6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.3.1.RELEASE-sources.jar",
          "url": "spring-boot-starter-tomcat-2.3.1.RELEASE-sources.jar",
          "size": 4789,
          "sha512": "d5d22c0f665534e45ecc9bb74fb54e4ac79fc7b45d2446b560ad17c17a827933d6782aa8e0fefaf0ee4c3ad21d59ac7f0e7cec870f1d4fa57e14994542039c7e",
          "sha256": "24789d7c76ee2b54cd8393e524af5e0e9580d303a9f4a565923fda893e3e49c4",
          "sha1": "5b599d0da04e724479c22daa47f9bfd62533a2e9",
          "md5": "5bc0e688d3a1a954d479aca239644f6c"
        }
      ]
    }
  ]
}
