{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.8.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7.jar",
          "url": "spring-boot-starter-test-2.5.7.jar",
          "size": 4793,
          "sha512": "88916a6c7b9c5ffad9fa1c4d693c30de4c5fdff0c8b57024ed24ae47b91c8ce92378ab0e34b069d58ecce79d0c28f475203e266a543e49a45fc761a2e75a2ebc",
          "sha256": "9b00b929af38ad53a90870c176d5529a94bd0a37b1112184216742d49943a3d5",
          "sha1": "4676cc735f832836226e18c1be7cba8374895887",
          "md5": "4a4019c880690536fd5c955e3cbabd37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.5.7"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.8.3"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7.jar",
          "url": "spring-boot-starter-test-2.5.7.jar",
          "size": 4793,
          "sha512": "88916a6c7b9c5ffad9fa1c4d693c30de4c5fdff0c8b57024ed24ae47b91c8ce92378ab0e34b069d58ecce79d0c28f475203e266a543e49a45fc761a2e75a2ebc",
          "sha256": "9b00b929af38ad53a90870c176d5529a94bd0a37b1112184216742d49943a3d5",
          "sha1": "4676cc735f832836226e18c1be7cba8374895887",
          "md5": "4a4019c880690536fd5c955e3cbabd37"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7.jar",
          "url": "spring-boot-starter-test-2.5.7.jar",
          "size": 4793,
          "sha512": "88916a6c7b9c5ffad9fa1c4d693c30de4c5fdff0c8b57024ed24ae47b91c8ce92378ab0e34b069d58ecce79d0c28f475203e266a543e49a45fc761a2e75a2ebc",
          "sha256": "9b00b929af38ad53a90870c176d5529a94bd0a37b1112184216742d49943a3d5",
          "sha1": "4676cc735f832836226e18c1be7cba8374895887",
          "md5": "4a4019c880690536fd5c955e3cbabd37"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7.jar",
          "url": "spring-boot-starter-test-2.5.7.jar",
          "size": 4793,
          "sha512": "88916a6c7b9c5ffad9fa1c4d693c30de4c5fdff0c8b57024ed24ae47b91c8ce92378ab0e34b069d58ecce79d0c28f475203e266a543e49a45fc761a2e75a2ebc",
          "sha256": "9b00b929af38ad53a90870c176d5529a94bd0a37b1112184216742d49943a3d5",
          "sha1": "4676cc735f832836226e18c1be7cba8374895887",
          "md5": "4a4019c880690536fd5c955e3cbabd37"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7-javadoc.jar",
          "url": "spring-boot-starter-test-2.5.7-javadoc.jar",
          "size": 4744,
          "sha512": "15fabbbf0922fcd28a49bc83618be394924ae40fb0f639dc5792d3f8bc2196674ac3ccd200d7fa8dd9c67c562e90387299fea5b057400af1b71d9ba762d1efc1",
          "sha256": "c70bb03b4a7be146c36cc3472e1c84d0c8a92e3ca0452bc34c6be6b38e3435bc",
          "sha1": "8333adb7051229e02374c6f8580b0ba2f2d6e4e1",
          "md5": "5f3d2aa164f8bc44f2838bacf77e9ce6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.5.7-sources.jar",
          "url": "spring-boot-starter-test-2.5.7-sources.jar",
          "size": 4742,
          "sha512": "14624497a0c79aec3b3b0b2b82c0a992956bf51b24de96d9a3865e28eafb6b553df5d3a2fa51d3d2eb9e048a080b08de8ce5d819fb12e30b3b75ff39fa805396",
          "sha256": "77b8bca1499aa5757e09ce29be2c477c22591fef72d4dd5c8285a06d1068e225",
          "sha1": "27cb5bcfaa12106ac367393ea11a591526e01942",
          "md5": "f60ebd38125db0566954ac3e7a5c9caf"
        }
      ]
    }
  ]
}
