{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "5.3.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.13.jar",
          "url": "spring-context-5.3.13.jar",
          "size": 1269453,
          "sha512": "19d8050a9bb71bf967c8ef9eb360d160d1472ce574a73cf392774a81c155fbe275b91361f07de508bd3b3f56b7f0769606d07c673f42cc3e93fa977341a596bb",
          "sha256": "90a5eeff7d1b3b7d407c9697c9a7b6c6ad47d3b391617011974aaa980d6c7e55",
          "sha1": "e328db1c30ffe1c58328e4ab42cd3855a5307469",
          "md5": "222fd2edbe684bc76d5536de7f921ef3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.13.jar",
          "url": "spring-context-5.3.13.jar",
          "size": 1269453,
          "sha512": "19d8050a9bb71bf967c8ef9eb360d160d1472ce574a73cf392774a81c155fbe275b91361f07de508bd3b3f56b7f0769606d07c673f42cc3e93fa977341a596bb",
          "sha256": "90a5eeff7d1b3b7d407c9697c9a7b6c6ad47d3b391617011974aaa980d6c7e55",
          "sha1": "e328db1c30ffe1c58328e4ab42cd3855a5307469",
          "md5": "222fd2edbe684bc76d5536de7f921ef3"
        }
      ]
    }
  ]
}
