{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "2.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "tpcfyj3xqnh7rnj6nen6lrx2la"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.5.7.jar",
          "url": "spring-boot-2.5.7.jar",
          "size": 1393186,
          "sha512": "da579fa5d16d0cdc50e9f35d8b73cb1bdcd98bf4871ce81ba7eb2b306ddbc105ba57aad1d934fb0e5a79e162a257c3c492cc53adb8ddad24187bf8aa7b7856ee",
          "sha256": "c22b4c15d5e59712e84cb4f56e494cb0f77347e0c8e6cf6194d25b808c209a92",
          "sha1": "04baa2219c115fac0fa3ebc73aa067130738879e",
          "md5": "78412db66c09018b1fb01111d7595227"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.13"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.5.7.jar",
          "url": "spring-boot-2.5.7.jar",
          "size": 1393186,
          "sha512": "da579fa5d16d0cdc50e9f35d8b73cb1bdcd98bf4871ce81ba7eb2b306ddbc105ba57aad1d934fb0e5a79e162a257c3c492cc53adb8ddad24187bf8aa7b7856ee",
          "sha256": "c22b4c15d5e59712e84cb4f56e494cb0f77347e0c8e6cf6194d25b808c209a92",
          "sha1": "04baa2219c115fac0fa3ebc73aa067130738879e",
          "md5": "78412db66c09018b1fb01111d7595227"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.5.7-javadoc.jar",
          "url": "spring-boot-2.5.7-javadoc.jar",
          "size": 1988298,
          "sha512": "8eef34aa34e1c41e69686d0d6ddbaac490d6bb0ff46608347d9d652f49fb454d16f6063c773b9f1e3e5450dac6975433f2d770b74afefe10a140ff08791685a1",
          "sha256": "afec6a4d24a2ed367b48f465b5a319e4792ef7d92559116cbfa32f20194f8809",
          "sha1": "ab4091fee212fafbfb0264fbe396f44f808d0018",
          "md5": "54ee830e90c2dbad0adaee47849ba5a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.5.7-sources.jar",
          "url": "spring-boot-2.5.7-sources.jar",
          "size": 992542,
          "sha512": "4be1efab46be26610c40dd5dd9c6e6a78d0010368f12f7e40aee626fca84c4c09d875e8db096eb99b39fa2777cdc59576a670e598142385bb99436bb58458fe6",
          "sha256": "31633195bab31d933e8973efac3ff41b7e620c32f162fdb9fbad787a516af471",
          "sha1": "c2e16b442e35489f8f4434927506c77cb01f44a9",
          "md5": "8b723cce490db2cbeac855dd51cdf195"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-2.5.7.jar",
          "url": "spring-boot-2.5.7.jar",
          "size": 1393186,
          "sha512": "da579fa5d16d0cdc50e9f35d8b73cb1bdcd98bf4871ce81ba7eb2b306ddbc105ba57aad1d934fb0e5a79e162a257c3c492cc53adb8ddad24187bf8aa7b7856ee",
          "sha256": "c22b4c15d5e59712e84cb4f56e494cb0f77347e0c8e6cf6194d25b808c209a92",
          "sha1": "04baa2219c115fac0fa3ebc73aa067130738879e",
          "md5": "78412db66c09018b1fb01111d7595227"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "2.5.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.5.7.jar",
          "url": "spring-boot-2.5.7.jar",
          "size": 1393186,
          "sha512": "da579fa5d16d0cdc50e9f35d8b73cb1bdcd98bf4871ce81ba7eb2b306ddbc105ba57aad1d934fb0e5a79e162a257c3c492cc53adb8ddad24187bf8aa7b7856ee",
          "sha256": "c22b4c15d5e59712e84cb4f56e494cb0f77347e0c8e6cf6194d25b808c209a92",
          "sha1": "04baa2219c115fac0fa3ebc73aa067130738879e",
          "md5": "78412db66c09018b1fb01111d7595227"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "2.5.7"
        }
      ]
    }
  ]
}
